### ISSUE TITLE
更改网络问题

### ISSUE THREAD

**Issue by zzzz737** [bubbliiiing/efficientdet-pytorch#13]
大佬，我把这个backbone换成了yolov5的backbone，训练之后loss很低，但是map测试很差，大佬能给点意见参考参考是为什么吗？

**Comment by bubbliiiing** [comment]
没用预训练权重吧？

**Comment by zzzz737** [comment]
> 没用预训练权重吧？

的确没用预训练权重，因为换了backbone，预训练权重不好迁移，但是没用预训练权重不至于结果差距太大吧，这是我的理解！

**Comment by bubbliiiing** [comment]
没有预训练权重都是这样的。

**Comment by zzzz737** [comment]
>

**Comment by zzzz737** [comment]
> 没有预训练权重都是这样的。

如果数据量够大，训练轮次增多，理论上是不是可以抵消这个没有预训练权重的不良影响？

**Comment by bubbliiiing** [comment]
提取到的特征还是差，效果肯定不如coco预训练的好，一般模型最差也有imagenet的预训练权重，否则不太行

**Comment by bubbliiiing** [comment]
选择一个优秀的初始化方式会有帮助，但是不会有很大的提升
