### ISSUE TITLE
训练自己的数据，mAP很低

### ISSUE THREAD

**Issue by xugc98** [bubbliiiing/efficientdet-pytorch#30]
作者您好，感谢你的工作。
我使用efficientdet-d3对其他数据集进行训练，效果比较差，可以请您帮忙分析一下吗？谢谢！
数据集是[铝型材表面缺陷检测数据](https://tianchi.aliyun.com/competition/entrance/231682/information)。
前30个epoch冻结主干，之后解冻训练，训练到val_loss不再降低。
map结果如下：
`Get map.

2.78% = 不导电 AP       ||      score_threhold=0.5 : F1=0.00 ; Recall=0.00% ; Precision=0.00%

0.00% = 喷流 AP         ||      score_threhold=0.5 : F1=0.00 ; Recall=0.00% ; Precision=0.00%

0.00% = 擦花 AP         ||      score_threhold=0.5 : F1=0.00% ; Recall=0.00% ; Precision=0.00%

38.01% = 杂色 AP        ||      score_threhold=0.5 : F1=0.11 ; Recall=5.56% ; Precision=100.00%

13.00% = 桔皮 AP        ||      score_threhold=0.5 : F1=0.00 ; Recall=0.00% ; Precision=0.00%

0.00% = 漆泡 AP         ||      score_threhold=0.5 : F1=0.00% ; Recall=0.00% ; Precision=0.00%

0.00% = 漏底 AP         ||      score_threhold=0.5 : F1=0.00 ; Recall=0.00% ; Precision=0.00%

5.01% = 脏点 AP         ||      score_threhold=0.5 : F1=0.14 ; Recall=10.84% ; Precision=21.43%

0.00% = 角位漏底 AP     ||      score_threhold=0.5 : F1=0.00% ; Recall=0.00% ; Precision=0.00%

0.00% = 起坑 AP         ||      score_threhold=0.5 : F1=0.00 ; Recall=0.00% ; Precision=0.00%

mAP = 5.88%

Get map done.`

每个epoch的val_loss如下：
`692.5821533203125
18.020043546503242
6.0580932082551895
2.9250449375672773
1.7247823729659573
1.1773547078623916
0.8997215122887583
0.7432047751816836
0.6556733747323354
0.5967527682130987
0.5552684529261156
0.5247120744351185
0.5120401086680817
0.490136006564805
0.48692420892643207
0.4789598101016247
0.46626631509174
0.47130427938519104
0.46737760531179834
0.4521835113339352
0.4599695607568278
0.45360165202256403
0.44911260993191693
0.4493762557253693
0.4430947389566537
0.44133371464682347
0.44138025108611945
0.44033303834272153
0.4294479764772184
0.4288688725368543
0.43481780243898505
0.4259181917825742
0.4300796524691048
0.41619802549926205
0.41009346857222156
0.4145459183561268
0.4220570447618392
0.4012312131530758
0.3930108847735978
0.4246373758998825
0.38846801557758853
0.39046983073340424
0.5298791383462611
0.3835990623251271
0.424211601240199
0.40973395342702296
0.374117885035143
0.3753899414537113
0.3762250279924318
0.3619030268668239
0.4167037764147146
0.37196493557473614
0.3779459266798265
0.3777198547691996
0.3685086570235331
0.3662413968635139
0.3724715964062445
0.37364781386594276
0.3646606824068881
0.40380949271259026
0.36690836080085876
0.39359222296903384
0.35407807564001476
0.35932715515147395
0.35652801939355794
0.3581762860126015
0.3570717303777364
0.3549506452712995
0.3696301862208256
0.36184008566857273
0.35130936827566195
0.35368453527786836
0.36518700056667647
0.34808981838399794
0.3540204591326304
0.35394072493732864
0.3597586819651856
0.35117012387447394
0.35453211001829427
0.338129321863847
0.354188849065286
0.3480956403733189
0.3560672045421244
0.3494431595665528
0.3579848694489963
0.3562058041344828
0.3504434914620065
0.36181518032368437
0.3520742502730729
0.3408385811568196
0.3392267982239154
0.34833704064419463
0.3375129512330489
0.34490444361051514
0.3474811746168937
0.3642430662997623
0.3400071593029286
0.3533157893359216
0.34791290949084863
0.35537530932186256
0.3504680647000448
0.3470999870949717
0.3505480893011858
0.351605375561474
0.35297540341740224
0.3379963515743391
0.34117161613235725
0.3530546065364311
0.35188829584686615
0.35485441400322004
0.3438295838492575
0.3458844947058763
0.35485429858872247
0.3565744514674393
0.34367825498165033
0.34764408359109467
0.35074018681449676
0.3437748175225596
0.34253188953804437
0.3441715170976831
0.3461703913870142
0.34832563582084963
0.3480878883222146
0.34780260700899274
0.3481335105068648
0.3435267209172694
0.34988239888491024
0.35219536335277024
0.3490558216876503
0.34662854827162043
0.3428226285961582
0.3569837624985558
0.34416547353699134
0.34747738218796786
0.34722422989113116
0.34134776695673147
0.343578678819893
0.3511959823654659
0.3519623815012512
0.34963406944897635
0.3476591583118955
0.34318768255301374
0.3484093218819419
0.35494244101443395
0.3509057753010472
0.3456782892957997
0.3371015375118647
0.3482280739708178
0.3487955643447922
0.3454236375140165
0.35292010598663076
0.3519064793780224
0.3401252330461545
0.3439494139278558
0.34353317512171483
0.34736122029708394
0.3405051428491055
0.34928369027242734
0.34589640301332547
0.34704446495135327
0.348259352842596
0.34758604331803855
0.34305048622746964
0.3531607194428346
0.3395370377311066
0.3502034348950012
0.3446665857988062
0.3422466347605657
0.34934172028703475
0.35288102302088664
0.35932373247151056
0.3504922179255023
0.3531327823093578
0.3520925745868416
0.3523084268029501
0.34706903154503055
0.35040349913622015
0.3543376238432838
0.3538556429766007
0.34093494554842585
0.3473847135901451
0.3451451262764966
0.34536995963930195
0.3503570426533471
0.34914408012557385
0.3532811352399303
0.34506166659629167
0.3482327019489968
0.3509918149393886
0.3524799474806928
0.35067986360570386
0.3517061372134668
0.3485593108543709
0.3451726289827432
0.34738497355424647
0.34392267045801256
0.3420782624674377
0.33875321841506817
0.347360303236255
0.3521433267186382
0.3485356454473378
0.34775876684753754
0.3512924103094126
0.3482155179632689
0.3382312229264583
0.35628125399573524
0.34736081468525215
0.3492826893369653
0.3421760888964827
0.3456490655610366
0.34405294005105747
0.34908889931862924
0.34774825335549775
0.35118296286508216
0.3519998987886443
0.3402652802474018
0.34220543765087624
0.34587571233399766
`

**Comment by xugc98** [comment]
刚检查代码发现是数据bbox格式转换的bug    o(╥﹏╥)o

**Comment by bubbliiiing** [comment]
啊这。加油
